"""gRPC transport for TAPI (spec §8.3).

    gRPC for request/response and streaming; Apache Arrow Flight for bulk
    columnar transfer; WebSocket for browser clients.

The third transport over one data path. `LocalTapi` answers all of them, so
a client choosing gRPC over HTTP gets the same answer to the same question —
a transport that could see something the others could not would be a second
source of truth wearing a protocol as a disguise.

Bulk export deliberately is **not** here. It lives on Arrow Flight
(`treble.tapi.flight`), which is what §8.3 says bulk columnar transfer is
for, and putting a second bulk path here would mean two places to enforce
the redistribution guard and one of them eventually forgotten.

**Loopback by default**, like the HTTP and Flight servers. There is no
authentication anywhere in this system yet; §22.1's entitlement model —
passkeys, per-user entitlements, OIDC, audit logging — does not exist, so a
routable gRPC server would be an unauthenticated data tap.

The stubs this imports are generated by `make proto` and are not committed.
See `proto/tapi.proto` for why.
"""

from __future__ import annotations

from concurrent import futures
from datetime import UTC, datetime

import grpc

from treble.core.identifiers import SecurityQuery
from treble.plant.quotes import Firmness
from treble.tapi._generated import tapi_pb2, tapi_pb2_grpc
from treble.tapi.contribution import (
    ContributionRejectedError,
    ContributionRequest,
    ContributionService,
)
from treble.tapi.local import LocalTapi, SecurityNotFoundError

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8758


def _as_of(message: tapi_pb2.AsOf, context: grpc.ServicerContext) -> datetime:
    """The point-in-time cut, required and timezone-aware (I2).

    Missing or naive is an error rather than "now": a server that filled in
    its own clock would answer the same question differently for two
    clients, and neither would know it had happened.
    """
    if not message.timestamp:
        context.abort(
            grpc.StatusCode.INVALID_ARGUMENT,
            "as_of is required: every read in this system is point-in-time (I2), and a "
            "server-supplied 'now' would answer one question two ways",
        )
    try:
        parsed = datetime.fromisoformat(message.timestamp)
    except ValueError:
        context.abort(
            grpc.StatusCode.INVALID_ARGUMENT, f"as_of {message.timestamp!r} is not RFC 3339"
        )
    if parsed.tzinfo is None:
        context.abort(
            grpc.StatusCode.INVALID_ARGUMENT,
            "as_of must be timezone-aware; a naive timestamp makes the cut depend on the "
            "server's timezone",
        )
    return parsed


def _security(message: tapi_pb2.SecurityQuery) -> SecurityQuery | None:
    if not message.ticker:
        return None
    fields: dict[str, str] = {"ticker": message.ticker}
    if message.key:
        fields["key"] = message.key
    if message.venue:
        fields["venue"] = message.venue
    return SecurityQuery.model_validate(fields)


class RefDataService(tapi_pb2_grpc.RefDataServicer):  # type: ignore[misc]
    """`//trb/refdata` — current values and series."""

    def __init__(self, tapi: LocalTapi) -> None:
        self._tapi = tapi

    def GetReferenceData(  # noqa: N802 - the name is the proto's
        self, request: tapi_pb2.ReferenceDataRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.ReferenceDataResponse:
        as_of = _as_of(request.as_of, context)
        security = _security(request.security)
        values = []
        for mnemonic in request.mnemonics:
            try:
                result = self._tapi.field(security, mnemonic, dict(request.overrides), as_of=as_of)
            except SecurityNotFoundError as error:
                context.abort(grpc.StatusCode.NOT_FOUND, str(error))
            except (KeyError, NotImplementedError) as error:
                # A field that is unknown, or known and unwired, is an error
                # rather than a blank. A blank reads as "not reported".
                context.abort(grpc.StatusCode.INVALID_ARGUMENT, f"{mnemonic}: {error}")
            values.append(_field_value(mnemonic, result))
        return tapi_pb2.ReferenceDataResponse(values=values)

    def GetSeries(  # noqa: N802
        self, request: tapi_pb2.SeriesRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.SeriesResponse:
        as_of = _as_of(request.as_of, context)
        rows = self._tapi.series(_security(request.security), request.binding, as_of=as_of)
        return tapi_pb2.SeriesResponse(
            rows=[
                tapi_pb2.SeriesRow(cells=["" if cell is None else str(cell) for cell in row])
                for row in rows
            ]
        )


def _field_value(mnemonic: str, result: object) -> tapi_pb2.FieldValue:
    """Map a FieldResult onto the wire type.

    `has_value` is explicit because proto3 cannot distinguish an absent
    double from 0.0, and a missing figure rendered as zero is the exact
    failure this system exists to prevent.
    """
    value = getattr(result, "value", None)
    message = tapi_pb2.FieldValue(mnemonic=mnemonic, has_value=value is not None)
    if isinstance(value, int | float) and not isinstance(value, bool):
        message.number = float(value)
    elif value is not None:
        message.text = str(value)
    for attribute in ("provenance_id", "effective_from", "effective_to"):
        held = getattr(result, attribute, None)
        if held is not None:
            setattr(message, attribute, str(held))
    message.stale = bool(getattr(result, "stale", False))
    return message


class FldsService(tapi_pb2_grpc.FldsServicer):  # type: ignore[misc]
    """`//trb/flds` — the field dictionary."""

    def __init__(self, tapi: LocalTapi) -> None:
        self._tapi = tapi

    def SearchFields(  # noqa: N802
        self, request: tapi_pb2.FieldSearchRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.FieldSearchResponse:
        limit = request.limit or 50
        found = self._tapi.search_fields(request.query, limit=limit)
        return tapi_pb2.FieldSearchResponse(
            fields=[
                tapi_pb2.FieldDescription(
                    mnemonic=definition.mnemonic,
                    description=definition.description,
                    field_type=definition.field_type.value,
                    sources=list(definition.sources),
                )
                for definition in found
            ]
        )


class InstrumentsService(tapi_pb2_grpc.InstrumentsServicer):  # type: ignore[misc]
    """`//trb/instruments` — identifier resolution."""

    def __init__(self, tapi: LocalTapi) -> None:
        self._tapi = tapi

    def Resolve(  # noqa: N802
        self, request: tapi_pb2.ResolveRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.ResolveResponse:
        security = _security(request.security)
        if security is None:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "a security is required")
            # Unreachable: `abort` raises. Stated so the type narrows, and
            # so a future grpc that let `abort` return could not fall
            # through into `resolve(None)`.
            raise AssertionError("abort did not raise")
        try:
            return tapi_pb2.ResolveResponse(subject=str(self._tapi.resolve(security)))
        except SecurityNotFoundError as error:
            # NOT_FOUND, never an empty subject: a mistyped identifier that
            # resolved to "" would render a screen of dashes indistinguishable
            # from a real instrument with no data.
            context.abort(grpc.StatusCode.NOT_FOUND, str(error))


_FIRMNESS = {
    tapi_pb2.FIRMNESS_INDICATIVE: Firmness.INDICATIVE,
    tapi_pb2.FIRMNESS_EXECUTABLE: Firmness.EXECUTABLE,
}


class ContribService(tapi_pb2_grpc.ContribServicer):  # type: ignore[misc]
    """`//trb/contrib` — the contributed network's write path (spec §2.2)."""

    def __init__(self, contributions: ContributionService) -> None:
        self._contributions = contributions

    def Contribute(  # noqa: N802
        self, request: tapi_pb2.ContributeRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.ContributeResponse:
        firmness = _FIRMNESS.get(request.firmness)
        if firmness is None:
            # proto3 gives every enum a zero value, so an unset field arrives
            # as FIRMNESS_UNSPECIFIED. Rejected rather than defaulted: either
            # default is wrong half the time — one presents an opinion as a
            # commitment, the other discards what makes a quote actionable.
            context.abort(
                grpc.StatusCode.INVALID_ARGUMENT,
                "firmness must be INDICATIVE or EXECUTABLE; an unstated quote is an "
                "opinion presented as a commitment, or the reverse",
            )

        received_at = datetime.now(UTC)
        try:
            quote = self._contributions.contribute(
                ContributionRequest(
                    subject=request.subject,
                    contributor=request.contributor,
                    firmness=firmness,
                    # `has_*` guards exist because proto3 cannot tell an
                    # absent double from 0.0, and "no bid" is not "a bid of
                    # nothing".
                    bid=request.bid if request.has_bid else None,
                    ask=request.ask if request.has_ask else None,
                    bid_size=request.bid_size if request.has_bid_size else None,
                    ask_size=request.ask_size if request.has_ask_size else None,
                    quoted_at=(
                        datetime.fromisoformat(request.quoted_at) if request.quoted_at else None
                    ),
                ),
                received_at=received_at,
            )
        except ContributionRejectedError as error:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, str(error))
        except ValueError as error:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, f"malformed contribution: {error}")

        book = self._contributions.book(request.subject, as_of=quote.quoted_at)
        tcmp_bid, tcmp_ask = book.tcmp
        tgn_bid, tgn_ask = book.tgn
        response = tapi_pb2.ContributeResponse(
            accepted=True,
            subject=str(quote.subject),
            contributor=quote.contributor,
            quoted_at=quote.quoted_at.isoformat(),
            contributors=len(book.quotes),
        )
        for name, value in (
            ("tcmp_bid", tcmp_bid),
            ("tcmp_ask", tcmp_ask),
            ("tgn_bid", tgn_bid),
            ("tgn_ask", tgn_ask),
        ):
            if value is not None:
                setattr(response, f"has_{name}", True)
                setattr(response, name, value)
        return response


class TqlService(tapi_pb2_grpc.TqlServicer):  # type: ignore[misc]
    """`//trb/tql` — query execution."""

    def __init__(self, tapi: LocalTapi) -> None:
        self._tapi = tapi

    def Execute(  # noqa: N802
        self, request: tapi_pb2.TqlRequest, context: grpc.ServicerContext
    ) -> tapi_pb2.TqlResponse:
        as_of = _as_of(request.as_of, context)
        rows = self._tapi.series(None, f"tql:{request.query}", as_of=as_of)
        # A query that could not run comes back with its reason in `error`
        # rather than as zero rows: "no matches" and "the query was invalid"
        # must not look the same to a client.
        if len(rows) == 1 and len(rows[0]) == 1 and str(rows[0][0]).startswith("query failed"):
            return tapi_pb2.TqlResponse(error=str(rows[0][0]))
        return tapi_pb2.TqlResponse(
            rows=[
                tapi_pb2.SeriesRow(cells=["" if cell is None else str(cell) for cell in row])
                for row in rows
            ]
        )


def create_server(
    tapi: LocalTapi,
    *,
    contributions: ContributionService | None = None,
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
    max_workers: int = 8,
) -> grpc.Server:
    """Build the gRPC server. Bound but not started."""
    service = contributions or tapi.contributions
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=max_workers))
    tapi_pb2_grpc.add_RefDataServicer_to_server(RefDataService(tapi), server)
    tapi_pb2_grpc.add_FldsServicer_to_server(FldsService(tapi), server)
    tapi_pb2_grpc.add_InstrumentsServicer_to_server(InstrumentsService(tapi), server)
    tapi_pb2_grpc.add_ContribServicer_to_server(ContribService(service), server)
    tapi_pb2_grpc.add_TqlServicer_to_server(TqlService(tapi), server)
    server.add_insecure_port(f"{host}:{port}")
    return server


def serve(
    tapi: LocalTapi, *, host: str = DEFAULT_HOST, port: int = DEFAULT_PORT
) -> None:  # pragma: no cover - process entry point
    """Run until terminated.

    `add_insecure_port` is accurate rather than careless: there is no
    transport security and no authentication, which is exactly why the
    default host is loopback and must stay there until §22.1 exists.
    """
    server = create_server(tapi, host=host, port=port)
    server.start()
    server.wait_for_termination()


__all__ = [
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "ContribService",
    "FldsService",
    "InstrumentsService",
    "RefDataService",
    "TqlService",
    "create_server",
    "serve",
]
