"""Build `Treble Tracker Terminal.app` — a double-clickable TUI launcher.

Not the desktop client. The spec's desktop surface (4) is the Tauri shell
in `apps/desktop`, which is built and installed by `make desktop-install`
and is the application to open normally.

This bundle exists because the TUI is a genuinely different surface, not
a fallback: it runs over SSH, in tmux, and on a machine with no WebView.
Its name and bundle identifier are deliberately distinct so the two never
overwrite each other in ~/Applications.

The bundle is generated rather than committed as binary: `make app`
rebuilds it, so it can never drift from the code it launches.
"""

from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

APP_NAME = "Treble Tracker Terminal"
BUNDLE_ID = "org.trebletracker.workstation"

LAUNCHER = """#!/bin/bash
# Generated by scripts/make_app.py — do not edit; run `make app` instead.
#
# Opens the workstation in a Terminal window. The repo path is baked in at
# build time so the bundle is self-contained from the user's point of view.
REPO="{repo}"
VENV="$REPO/.venv/bin/treble"

if [ ! -x "$VENV" ]; then
  MSG="The virtual environment is missing.\\n\\nRun: cd {repo} && make setup"
  osascript -e "display alert \\"Treble Tracker\\" message \\"$MSG\\" as critical"
  exit 1
fi

# A dense workstation needs room; ask Terminal for a large window.
osascript <<APPLESCRIPT
tell application "Terminal"
    activate
    set newWindow to do script "cd '$REPO' && exec '$VENV' tui"
    set number of columns of front window to 140
    set number of rows of front window to 45
    set current settings of front window to settings set "Pro"
end tell
APPLESCRIPT
"""


def build(repo: Path, destination: Path) -> Path:
    """Create the .app bundle. Returns its path."""
    bundle = destination / f"{APP_NAME}.app"
    if bundle.exists():
        shutil.rmtree(bundle)

    macos = bundle / "Contents" / "MacOS"
    resources = bundle / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    executable = macos / "treble-tracker"
    executable.write_text(LAUNCHER.format(repo=repo))
    executable.chmod(0o755)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "CFBundleExecutable": "treble-tracker",
        "CFBundlePackageType": "APPL",
        "CFBundleIconFile": "icon.icns",
        "LSMinimumSystemVersion": "13.0",
        # No network entitlements needed: the launcher only starts Terminal.
        "LSBackgroundOnly": False,
    }
    (bundle / "Contents" / "Info.plist").write_bytes(plistlib.dumps(info))

    icon = _make_icon(resources)
    if icon is None:
        # An iconless bundle still works; say so rather than failing the build.
        print("note: no icon generated (iconutil unavailable); bundle is iconless")

    return bundle


def _make_icon(resources: Path) -> Path | None:
    """Generate a simple icon from text if the toolchain allows.

    Returns None rather than raising: an icon is cosmetic and must not be
    able to break the build.
    """
    iconset = resources / "icon.iconset"
    iconset.mkdir(exist_ok=True)
    svg = iconset / "icon.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024">'
        '<rect width="1024" height="1024" rx="180" fill="#0a0a0a"/>'
        '<text x="512" y="600" font-family="Menlo,monospace" font-size="420" '
        'font-weight="bold" fill="#d78700" text-anchor="middle">TT</text>'
        '<rect x="180" y="700" width="664" height="14" fill="#00afd7"/>'
        "</svg>"
    )
    try:
        for size in (16, 32, 128, 256, 512):
            for scale, suffix in ((1, ""), (2, "@2x")):
                out = iconset / f"icon_{size}x{size}{suffix}.png"
                subprocess.run(  # noqa: S603
                    [
                        "/usr/bin/qlmanage",
                        "-t",
                        "-s",
                        str(size * scale),
                        "-o",
                        str(iconset),
                        str(svg),
                    ],
                    capture_output=True,
                    check=False,
                    timeout=30,
                )
                rendered = iconset / f"{svg.name}.png"
                if rendered.exists():
                    rendered.rename(out)
        result = subprocess.run(  # noqa: S603
            ["/usr/bin/iconutil", "-c", "icns", str(iconset), "-o", str(resources / "icon.icns")],
            capture_output=True,
            check=False,
            timeout=30,
        )
        shutil.rmtree(iconset, ignore_errors=True)
        icns = resources / "icon.icns"
        return icns if icns.exists() and result.returncode == 0 else None
    except (OSError, subprocess.SubprocessError):
        shutil.rmtree(iconset, ignore_errors=True)
        return None


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Applications"
    destination.mkdir(parents=True, exist_ok=True)
    bundle = build(repo, destination)
    print(f"built {bundle}")
    print("Open it from Applications, Spotlight, or drag it to the Dock.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
