"""gRPC transport for TAPI (spec §8.3).

Two things are being tested and only one of them is gRPC. The RPC plumbing
is Google's; what is this project's is that the third transport gives the
*same answers* as the other two, and that the schema being served is the one
declared in `proto/tapi.proto`.

`TestTheGeneratedCodeMatchesTheProto` is the kill-test. The stubs are
generated by `make proto` and never committed, precisely so they cannot
silently diverge from the proto beside them — and that guarantee is only
real if something checks it.
"""

from __future__ import annotations

import re
from datetime import UTC, date, datetime
from pathlib import Path

import grpc
import pytest

from treble.core.facts import Fact
from treble.core.identifiers import TUID
from treble.core.provenance import ExtractionMethod, Provenance
from treble.store.duck import DuckStore
from treble.tapi._generated import tapi_pb2, tapi_pb2_grpc
from treble.tapi.contribution import ContributionService
from treble.tapi.grpc_server import DEFAULT_HOST, create_server
from treble.tapi.local import LocalTapi

PROTO = Path(__file__).resolve().parents[2] / "proto" / "tapi.proto"
KNOWN = datetime(2026, 8, 1, 6, 0, tzinfo=UTC)
DAY = date(2026, 7, 31)
AS_OF = datetime(2026, 8, 3, 18, 0, tzinfo=UTC)
BOND = "cusip:912810UT3"


@pytest.fixture
def channel(tmp_path: Path):  # type: ignore[no-untyped-def]
    """A live server on an ephemeral loopback port."""
    store = DuckStore(tmp_path / "t.db")
    record = Provenance(
        source_system="fred",
        source_uri="https://example.invalid/fred",
        retrieved_at=KNOWN,
        method=ExtractionMethod.API,
        extractor_version="1",
        payload_hash="0" * 64,
    )
    store.write_provenance([record])
    store.write_facts(
        [
            Fact(
                subject=TUID("fred:DGS10"),
                field="PX_LAST",
                value=4.31,
                effective_from=DAY,
                effective_to=DAY,
                knowledge_from=KNOWN,
                provenance_id=record.id,
            )
        ]
    )
    # create_server binds its own port; ask the OS for a free one and read
    # back what it actually bound, so parallel test runs cannot collide.
    server = create_server(
        LocalTapi(store), contributions=ContributionService(), host=DEFAULT_HOST, port=0
    )
    port = server.add_insecure_port(f"{DEFAULT_HOST}:0")
    server.start()
    with grpc.insecure_channel(f"{DEFAULT_HOST}:{port}") as chan:
        yield chan
    server.stop(grace=None)


class TestTheGeneratedCodeMatchesTheProto:
    """The kill-test: proof that `make proto` ran and served this schema.

    The stubs are gitignored and regenerated on every `make check`, so the
    proto is the only contract. That is worth nothing unless something
    verifies the two agree — a stale or absent generation would otherwise
    keep compiling and keep serving a schema nobody declared, which is the
    exact failure this repository has now found five times.
    """

    def test_every_declared_service_is_generated(self) -> None:
        declared = set(re.findall(r"^service\s+(\w+)\s*\{", PROTO.read_text(), re.MULTILINE))
        generated = {
            name.removesuffix("Servicer")
            for name in dir(tapi_pb2_grpc)
            if name.endswith("Servicer") and not name.startswith("_")
        }
        assert declared, "no services found in the proto — has it moved?"
        assert declared == generated, (
            f"proto declares {sorted(declared)} but the generated stubs expose "
            f"{sorted(generated)}. Run `make proto`."
        )

    def test_every_declared_rpc_is_generated(self) -> None:
        """Service names matching is not enough — a renamed RPC would slip
        through a check that only compared the services."""
        text = PROTO.read_text()
        for service, body in re.findall(r"service\s+(\w+)\s*\{(.*?)\}", text, re.DOTALL):
            declared = set(re.findall(r"rpc\s+(\w+)\s*\(", body))
            servicer = getattr(tapi_pb2_grpc, f"{service}Servicer")
            generated = {n for n in dir(servicer) if not n.startswith("_")}
            assert declared <= generated, f"{service}: {declared - generated} not generated"

    def test_firmness_unspecified_exists_and_is_zero(self) -> None:
        """proto3 forces a zero value on every enum. It exists here so the
        server can *reject* it — the point is that an unstated firmness is
        never silently read as one of the real values."""
        assert tapi_pb2.FIRMNESS_UNSPECIFIED == 0


class TestTheSameAnswersAsTheOtherTransports:
    def test_reference_data_comes_back(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.RefDataStub(channel)
        response = stub.GetReferenceData(
            tapi_pb2.ReferenceDataRequest(
                security=tapi_pb2.SecurityQuery(ticker="DGS10", key="Index"),
                mnemonics=["PX_LAST"],
                as_of=tapi_pb2.AsOf(timestamp=AS_OF.isoformat()),
            )
        )
        assert len(response.values) == 1
        assert response.values[0].has_value is True
        assert response.values[0].number == pytest.approx(4.31)

    def test_a_missing_value_is_not_zero(self, channel: grpc.Channel) -> None:
        """`has_value` exists because proto3 cannot distinguish an absent
        double from 0.0, and a missing figure rendered as zero is the exact
        failure this system exists to prevent."""
        stub = tapi_pb2_grpc.RefDataStub(channel)
        response = stub.GetReferenceData(
            tapi_pb2.ReferenceDataRequest(
                security=tapi_pb2.SecurityQuery(ticker="DGS2", key="Index"),
                mnemonics=["PX_LAST"],
                as_of=tapi_pb2.AsOf(timestamp=AS_OF.isoformat()),
            )
        )
        assert response.values[0].has_value is False
        assert response.values[0].number == 0.0  # the proto default, not a price

    def test_field_search_works(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.FldsStub(channel)
        response = stub.SearchFields(tapi_pb2.FieldSearchRequest(query="price", limit=5))
        assert response.fields


class TestPointInTimeIsEnforced:
    """I2 on the wire. A transport that let `as_of` be optional would answer
    one question two ways depending on the server's clock."""

    def test_a_missing_as_of_is_refused(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.RefDataStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.GetReferenceData(
                tapi_pb2.ReferenceDataRequest(
                    security=tapi_pb2.SecurityQuery(ticker="DGS10", key="Index"),
                    mnemonics=["PX_LAST"],
                )
            )
        assert raised.value.code() is grpc.StatusCode.INVALID_ARGUMENT
        assert "as_of is required" in raised.value.details()

    def test_a_naive_as_of_is_refused(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.RefDataStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.GetReferenceData(
                tapi_pb2.ReferenceDataRequest(
                    security=tapi_pb2.SecurityQuery(ticker="DGS10", key="Index"),
                    mnemonics=["PX_LAST"],
                    as_of=tapi_pb2.AsOf(timestamp="2026-08-03T12:00:00"),
                )
            )
        assert "timezone-aware" in raised.value.details()

    def test_a_read_before_the_facts_were_known_sees_nothing(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.RefDataStub(channel)
        response = stub.GetReferenceData(
            tapi_pb2.ReferenceDataRequest(
                security=tapi_pb2.SecurityQuery(ticker="DGS10", key="Index"),
                mnemonics=["PX_LAST"],
                as_of=tapi_pb2.AsOf(timestamp=datetime(2026, 7, 1, tzinfo=UTC).isoformat()),
            )
        )
        assert response.values[0].has_value is False


class TestContribution:
    def test_a_quote_is_accepted_and_the_composites_echoed(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.ContribStub(channel)
        response = stub.Contribute(
            tapi_pb2.ContributeRequest(
                subject=BOND,
                contributor="Dealer A",
                firmness=tapi_pb2.FIRMNESS_EXECUTABLE,
                has_bid=True,
                bid=98.25,
                has_ask=True,
                ask=98.75,
            )
        )
        assert response.accepted is True
        assert response.contributors == 1
        assert (response.tcmp_bid, response.tcmp_ask) == pytest.approx((98.25, 98.75))

    def test_an_unstated_firmness_is_refused(self, channel: grpc.Channel) -> None:
        """The proto3 zero value must never be read as a real firmness.
        Defaulting either way is wrong half the time — one presents an
        opinion as a commitment, the other discards what makes a quote
        actionable."""
        stub = tapi_pb2_grpc.ContribStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.Contribute(
                tapi_pb2.ContributeRequest(
                    subject=BOND, contributor="Dealer A", has_bid=True, bid=98.25
                )
            )
        assert raised.value.code() is grpc.StatusCode.INVALID_ARGUMENT
        assert "firmness must be" in raised.value.details()

    def test_a_bid_of_zero_is_not_an_absent_bid(self, channel: grpc.Channel) -> None:
        """`has_bid` carries the distinction proto3 scalars cannot. Without
        it a quote sent with no bid would arrive as a bid of 0.0 and be
        refused as 'not a price' — or worse, accepted."""
        stub = tapi_pb2_grpc.ContribStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.Contribute(
                tapi_pb2.ContributeRequest(
                    subject=BOND,
                    contributor="Dealer A",
                    firmness=tapi_pb2.FIRMNESS_EXECUTABLE,
                    has_bid=False,
                    has_ask=False,
                )
            )
        assert "says nothing" in raised.value.details()

    def test_a_crossed_quote_is_refused_with_its_reason(self, channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.ContribStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.Contribute(
                tapi_pb2.ContributeRequest(
                    subject=BOND,
                    contributor="Dealer A",
                    firmness=tapi_pb2.FIRMNESS_EXECUTABLE,
                    has_bid=True,
                    bid=101.0,
                    has_ask=True,
                    ask=99.0,
                )
            )
        assert "crossed quote" in raised.value.details()


class TestResolution:
    def test_an_unknown_security_is_not_found_not_blank(self, channel: grpc.Channel) -> None:
        """NOT_FOUND rather than an empty subject: a mistyped identifier
        resolving to "" would render a screen of dashes indistinguishable
        from a real instrument with no data."""
        stub = tapi_pb2_grpc.InstrumentsStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.Resolve(
                tapi_pb2.ResolveRequest(
                    security=tapi_pb2.SecurityQuery(ticker="NOTAREALTICKER", key="Equity")
                )
            )
        assert raised.value.code() is grpc.StatusCode.NOT_FOUND


class TestNoNetworkSurfaceByDefault:
    def test_the_default_host_is_loopback(self) -> None:
        """No authentication exists anywhere in this system — §22.1's
        entitlement model is unbuilt — so a routable gRPC server would be an
        unauthenticated data tap."""
        assert DEFAULT_HOST == "127.0.0.1"

    def test_bulk_export_is_not_on_this_transport(self) -> None:
        """It lives on Arrow Flight, behind the redistribution guard. Two
        bulk paths would mean two places to enforce that guard and one of
        them eventually forgotten."""
        services = {n for n in dir(tapi_pb2_grpc) if n.endswith("Stub")}
        assert not any("export" in n.lower() or "bulk" in n.lower() for n in services)


def test_the_server_builds_without_a_contribution_service(tmp_path: Path) -> None:
    """Defaults to the TAPI instance's own book, so a caller cannot
    accidentally run a server whose contributions go somewhere else."""
    server = create_server(LocalTapi(DuckStore(tmp_path / "t.db")), port=0)
    assert isinstance(server, grpc.Server)


@pytest.fixture
def tape_channel(tmp_path: Path):  # type: ignore[no-untyped-def]
    """A server with a plant fed from the recorded Coinbase frames."""
    from treble.plant.bars import TickHistory
    from treble.plant.conflation import TickerPlant
    from treble.plant.venues import ticks_from_messages

    frames = (
        (Path(__file__).resolve().parents[1] / "fixtures" / "coinbase" / "ws_matches.jsonl")
        .read_text()
        .splitlines()
    )
    plant, history = TickerPlant(), TickHistory()
    for tick in ticks_from_messages(frames):
        plant.publish(tick)
        history.record(tick)

    server = create_server(
        LocalTapi(DuckStore(tmp_path / "t.db")),
        plant=plant,
        history=history,
        host=DEFAULT_HOST,
        port=0,
    )
    port = server.add_insecure_port(f"{DEFAULT_HOST}:0")
    server.start()
    with grpc.insecure_channel(f"{DEFAULT_HOST}:{port}") as chan:
        yield chan
    server.stop(grace=None)


BTC = "crypto:coinbase:BTC-USD"


class TestTheTapeServices:
    """§8.3's `mktdata`, `mktbar` and `mktvwap`, over real recorded prints."""

    def test_market_data_returns_the_current_image(self, tape_channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        response = stub.GetMarketData(tapi_pb2.MarketDataRequest(subject=BTC))
        assert response.has_price is True
        assert response.price > 0
        assert response.sequence > 0
        assert response.exchange_time.startswith("2026-")

    def test_an_instrument_with_no_prints_is_not_a_price_of_zero(
        self, tape_channel: grpc.Channel
    ) -> None:
        """`has_price` carries what proto3 scalars cannot. Without it a
        never-traded instrument arrives as a price of 0.0."""
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        response = stub.GetMarketData(tapi_pb2.MarketDataRequest(subject="crypto:coinbase:NOPE"))
        assert response.has_price is False
        assert response.price == 0.0

    def test_bars_come_back_with_their_vwap(self, tape_channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        response = stub.GetBars(tapi_pb2.BarRequest(subject=BTC, interval_seconds=60))
        assert response.bars
        for bar in response.bars:
            assert bar.low <= bar.open <= bar.high
            assert bar.has_vwap is True
            assert bar.low <= bar.vwap <= bar.high

    def test_the_partial_bar_is_flagged_on_the_wire(self, tape_channel: grpc.Channel) -> None:
        """A client drawing the unfinished interval beside completed ones
        shows a spurious drop on every refresh."""
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        response = stub.GetBars(tapi_pb2.BarRequest(subject=BTC, interval_seconds=3600))
        assert response.bars[-1].complete is False

    def test_a_zero_interval_is_refused(self, tape_channel: grpc.Channel) -> None:
        """Defaulting it would decide what a bar means for every client that
        forgot to say."""
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.GetBars(tapi_pb2.BarRequest(subject=BTC, interval_seconds=0))
        assert raised.value.code() is grpc.StatusCode.INVALID_ARGUMENT

    def test_an_unknown_subject_is_not_found_not_empty(self, tape_channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.GetBars(tapi_pb2.BarRequest(subject="crypto:coinbase:NOPE", interval_seconds=60))
        assert raised.value.code() is grpc.StatusCode.NOT_FOUND

    def test_vwap_is_volume_weighted_and_inside_the_range(self, tape_channel: grpc.Channel) -> None:
        stub = tapi_pb2_grpc.MktDataStub(tape_channel)
        response = stub.GetVwap(tapi_pb2.VwapRequest(subject=BTC))
        assert response.volume > 0
        assert response.trades > 0
        assert response.price > 0


class TestAServerWithNoTape:
    def test_the_tape_services_refuse_rather_than_returning_nothing(
        self, channel: grpc.Channel
    ) -> None:
        """'This deployment has no tape' and 'this instrument has not
        printed' are different answers, and the second is the more
        believable of the two."""
        stub = tapi_pb2_grpc.MktDataStub(channel)
        with pytest.raises(grpc.RpcError) as raised:
            stub.GetMarketData(tapi_pb2.MarketDataRequest(subject=BTC))
        assert raised.value.code() is grpc.StatusCode.FAILED_PRECONDITION
        assert "no ticker plant" in raised.value.details()
